import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import { Router, useRouter } from 'next/router';
import qs from 'qs';

import React from 'react'
import Tabbar from '../../components/Tabbar';
import { fetchArticles, fetchCategories } from '../../http';

const Category = ({categories}) => {  

  const formattedCategory = () => {
    return 'Test Category';
  };

  const router = useRouter()
  console.log(router.query.category);


  return (
    <>
      <Head>
        <title>Createevity {formattedCategory()} </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Tabbar categoriesArray={categories.items}/>
    </>
  )
}

export async function getServerSideProps({query}) {


  const options = {
    populate: ['author.avatar'],
    sort: ['id:desc'],
    filters: {
      category: {
        slug: query.category,
      },
    }
  };


  const queryString = qs.stringify(options);

  const dataArticle = await fetchArticles(queryString);

  console.log(dataArticle);

  const dataCategory = await fetchCategories();

  return {
    props: {
      categories: {
        items: dataCategory.data.data,
        pagination: dataCategory.data.meta.pagination
      },
    }
  }

}

export default Category


