import { Box, Text } from "@chakra-ui/react";
import ArticleList from "../components/ArticleList";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Tabbar from "../components/Tabbar";
import { fetchArticles, fetchCategories } from "../http";
import qs from 'qs';
import Head from "next/head";
import Pagination from "../components/Pagination";


export async function getServerSideProps(context) {


  const options = {
    populate: ['author.avatar'],
    sort: ['id:desc'],
  };

  const queryString = qs.stringify(options);
  // fetch articles
  const dataArticle = await fetchArticles(queryString);


  // fetch categories
  const dataCategory = await fetchCategories();

  // console.log(dataCategory.data.data);

  // console.log(queryString);

  return {
    props: {
      categories: {
        items: dataCategory.data.data
      },

      articles: {
        items: dataArticle.data.data,
        pagination: dataArticle.data.meta.pagination,
      }
    }
  }
}


export default function Home({ categories, articles }) {

  const { page,pageCount } = articles.pagination;

  return (
    <div>
      <Head>
        <title>Createevity Homepage</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabbar categoriesArray={categories.items} />
      <ArticleList articlesArray={articles.items} />
      <Pagination page={page} pageCount={pageCount} />
    </div>
  )
}
